CREATE TABLE IF NOT EXISTS Film (
                        Film_id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Name varchar(200) NOT NULL,
                        Description varchar(200) NOT NULL,
                        ReleaseDate date NOT NULL,
                        Duration int NOT NULL,
                        Rate int,
                        Rating_id int NOT NULL,
                        CONSTRAINT pk_Film PRIMARY KEY (Film_id)
                        );

CREATE TABLE IF NOT EXISTS Users (
                        User_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        Name varchar(200) NOT NULL,
                        Email varchar(200) NOT NULL,
                        Login varchar(50) NOT NULL,
                        Birthday date NOT NULL,
                        CONSTRAINT pk_User PRIMARY KEY (User_id),
                        CONSTRAINT uc_User_Email UNIQUE (Email)
);

CREATE TABLE IF NOT EXISTS Likes (
                        Like_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        User_id int NOT NULL,
                        Film_id int NOT NULL,
                        CONSTRAINT pk_Like PRIMARY KEY (Like_id)
);


CREATE TABLE IF NOT EXISTS FriendList (
                              FriendListId int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              User_id int NOT NULL,
                              FriendID int NOT NULL,
                              Status bool NOT NULL,
                              CONSTRAINT pk_FriendList PRIMARY KEY (FriendListId)
);

CREATE TABLE IF NOT EXISTS GenreLine (
                             GenreLineID int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             Film_id int NOT NULL,
                             GenreID int NOT NULL,
                             CONSTRAINT pk_GenreLine PRIMARY KEY (GenreLineID)
);

CREATE TABLE IF NOT EXISTS Genre (
                         GenreID int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         Name varchar(200) NOT NULL,
                         CONSTRAINT pk_Genre PRIMARY KEY (GenreID),
                         CONSTRAINT uc_Genre_Name UNIQUE (Name)
);

CREATE TABLE IF NOT EXISTS RatingMPA (
                             Rating_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             Name varchar(10) NOT NULL,
                             Description varchar(200) NOT NULL,
                             CONSTRAINT pk_RatingMPA PRIMARY KEY (Rating_id),
                             CONSTRAINT uc_RatingMPA_Name UNIQUE (Name)
);

ALTER TABLE Film ADD CONSTRAINT IF NOT EXISTS fk_Film_Rating_id FOREIGN KEY(Rating_id)
    REFERENCES RatingMPA (Rating_id) ON DELETE RESTRICT;

ALTER TABLE Likes ADD CONSTRAINT IF NOT EXISTS fk_Like_User_id FOREIGN KEY(User_id)
    REFERENCES Users (User_id);

ALTER TABLE Likes ADD CONSTRAINT IF NOT EXISTS fk_Like_FilmID FOREIGN KEY(Film_id)
    REFERENCES Film (Film_id) ON DELETE CASCADE;

ALTER TABLE FriendList ADD CONSTRAINT IF NOT EXISTS fk_Friendlist_User_id FOREIGN KEY(User_id)
    REFERENCES Users (User_id);

ALTER TABLE FriendList ADD CONSTRAINT IF NOT EXISTS fk_Friendship_FriendID FOREIGN KEY(FriendID)
    REFERENCES Users (User_id);

ALTER TABLE GenreLine ADD CONSTRAINT IF NOT EXISTS fk_GenreLine_FilmID FOREIGN KEY(Film_id)
    REFERENCES Film (Film_id) ON DELETE CASCADE;

ALTER TABLE GenreLine ADD CONSTRAINT IF NOT EXISTS fk_GenreLine_GenreID FOREIGN KEY(GenreID)
    REFERENCES Genre (GenreID) ON DELETE RESTRICT;

ALTER TABLE GenreLine ADD CONSTRAINT IF NOT EXISTS UC_GenreLine_GenreID_FilmID UNIQUE (GenreID, Film_id)
